import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
const write = (p, v) => {
  mkdirSync(p.substring(0, p.lastIndexOf("/")), { recursive: true });
  writeFileSync(p, JSON.stringify(v, null, 2));
};
const ids =
  "analytical creativity persistence stability independence leadership social_influence communication risk_tolerance money_orientation achievement_orientation recognition_need emotional_sensitivity relationship_stability adaptability career_mobility entrepreneurship organization_fit execution planning responsibility persuasion learning_speed specialist_orientation management_orientation resilience competition external_visibility networking decision_speed".split(
    " ",
  );
const labels =
  "분석력 창의성 지속력 안정지향 독립성 리더십 사회적영향 소통 위험감수 소득지향 성취지향 인정욕구 정서민감 관계안정 적응력 이동성 기업가성 조직적합 실행력 계획성 책임감 설득력 학습속도 전문가지향 관리지향 회복력 경쟁성 외부가시성 네트워킹 판단속도".split(
    " ",
  );
const traits = ids.map((id, i) => ({ id, label: labels[i], base: 50 }));
const occupations = [
  ["it", "Software / IT", "analytical specialist_orientation execution"],
  ["engineering", "Engineering", "analytical planning responsibility"],
  ["product", "Product / Planning", "planning communication execution"],
  ["sales", "Sales", "persuasion networking competition"],
  ["marketing", "Marketing", "creativity social_influence analytical"],
  ["finance", "Finance", "analytical stability responsibility"],
  ["consulting", "Consulting", "persuasion analytical external_visibility"],
  ["research", "Research", "learning_speed persistence specialist_orientation"],
  ["education", "Education", "communication responsibility persistence"],
  [
    "healthcare",
    "Healthcare",
    "responsibility emotional_sensitivity stability",
  ],
  ["public", "Public Sector", "organization_fit stability planning"],
  ["manufacturing", "Manufacturing", "execution responsibility persistence"],
  ["logistics", "Logistics", "planning execution decision_speed"],
  ["design", "Design", "creativity specialist_orientation adaptability"],
  ["creative", "Creative", "creativity independence external_visibility"],
  ["legal", "Legal", "analytical persuasion responsibility"],
  [
    "business",
    "Entrepreneurship",
    "entrepreneurship risk_tolerance leadership",
  ],
  ["operations", "Operations", "organization_fit planning execution"],
  ["hr", "HR", "communication relationship_stability management_orientation"],
  ["service", "Service", "communication adaptability resilience"],
].map(([id, label, keys]) => ({
  id,
  label,
  profile: Object.fromEntries(keys.split(" ").map((k) => [k, 80])),
}));
const actionsText = [
  [
    "BUILD_LEADERSHIP_EXPERIENCE",
    "작은 팀의 결과를 책임지세요.",
    "30일 안에 3명 규모 프로젝트를 제안하고 역할과 마감일을 문서화하세요.",
    "leadership",
    18,
  ],
  [
    "BUILD_EXTERNAL_VISIBILITY",
    "성과를 회사 밖으로 꺼내세요.",
    "14일 안에 민감정보를 제거한 문제·해결·수치 사례를 1편 공개하세요.",
    "external_visibility",
    20,
  ],
  [
    "BUILD_SKILL",
    "직무를 하나 고르고 증거를 만드세요.",
    "30일 안에 목표 공고 10개를 비교하고 공통 기술로 결과물 1개를 완성하세요.",
    "specialist_orientation",
    15,
  ],
  [
    "GAIN_EXPERIENCE",
    "지원보다 먼저 작은 실무를 완주하세요.",
    "6주 안에 실제 사용자가 있는 프로젝트나 유급 단기 업무를 완수하세요.",
    "execution",
    15,
  ],
  [
    "VALIDATE_BUSINESS",
    "퇴사 전에 고객부터 확인하세요.",
    "2주 동안 잠재 고객 10명을 인터뷰하고 유료 의향 3건을 확인하세요.",
    "entrepreneurship",
    12,
  ],
  [
    "BUILD_RUNWAY",
    "선택할 수 있는 생활비를 확보하세요.",
    "이번 주 고정지출을 정리하고 6개월 비상자금 계획을 세우세요.",
    "stability",
    12,
  ],
  [
    "DOCUMENT_IMPACT",
    "업무량 대신 결과를 기록하세요.",
    "이번 주 성과 3건을 전후 수치와 담당 범위로 정리하세요.",
    "achievement_orientation",
    10,
  ],
  [
    "NEGOTIATE",
    "협상 자료를 만드세요.",
    "30일 안에 시장 공고 10개와 본인 성과를 1장으로 정리하세요.",
    "persuasion",
    12,
  ],
  [
    "BUILD_NETWORK",
    "연락할 사람을 만드세요.",
    "매주 동종 직무 1명과 업무 이야기를 나누고 배운 점을 기록하세요.",
    "networking",
    12,
  ],
  [
    "LEARN",
    "학습을 일정에 고정하세요.",
    "4주간 주 3시간을 배정하고 매주 결과물로 검증하세요.",
    "learning_speed",
    10,
  ],
];
const extra = [
  "분석 가설을 검증하세요",
  "초안 3개를 비교하세요",
  "완료 기준을 정하세요",
  "혼자 결정할 범위를 정하세요",
  "발표를 녹화하세요",
  "회의 결론을 문서화하세요",
  "위험 한도를 정하세요",
  "소득원을 점검하세요",
  "피드백을 요청하세요",
  "감정 기록을 남기세요",
  "약속을 지키는 구조를 만드세요",
  "다른 직무를 체험하세요",
  "인수인계 문서를 만드세요",
  "일정 오차를 측정하세요",
  "책임 범위를 합의하세요",
  "전문 주제를 좁히세요",
  "위임할 업무를 정하세요",
  "회복 시간을 확보하세요",
  "비교 기준을 정하세요",
  "결정 기한을 정하세요",
];
const actions = [
  ...actionsText.map(([id, title, detail, trait, delta]) => ({
    id,
    title,
    detail,
    trait,
    delta,
  })),
  ...extra.map((title, i) => ({
    id: `ACTION_${i + 11}`,
    title,
    detail: `앞으로 14일 동안 '${title.replace("세요", "기")}'를 실행하고 결과와 다음 수정 사항을 한 페이지로 기록하세요.`,
    trait: ids[i],
    delta: 8,
  })),
];
const mappings = [];
const add = (feature, trait, weight) =>
  mappings.push({ id: `map_${mappings.length + 1}`, feature, trait, weight });
[
  ["experience", "execution", 26],
  ["experience", "specialist_orientation", 28],
  ["experience", "responsibility", 15],
  ["experience", "persistence", 15],
  ["management", "leadership", 40],
  ["management", "management_orientation", 35],
  ["management", "persuasion", 20],
  ["visibility", "external_visibility", 45],
  ["visibility", "social_influence", 25],
  ["network", "networking", 35],
  ["network", "communication", 20],
  ["learning", "learning_speed", 35],
  ["learning", "adaptability", 20],
  ["runway", "stability", 25],
  ["business", "entrepreneurship", 35],
  ["business", "risk_tolerance", 20],
  ["mobility", "career_mobility", 25],
  ["education", "analytical", 12],
  ["level", "achievement_orientation", 15],
  ["experience", "planning", 12],
].forEach((v) => add(...v));
ids.forEach((id) => add(`self_${id}`, id, 30));
[
  ["head_line_length", "analytical", 5],
  ["heart_line_length", "communication", 4],
  ["life_line_length", "persistence", 4],
  ["fate_line_strength", "execution", 4],
  ["wood", "creativity", 3],
  ["fire", "social_influence", 3],
  ["earth", "stability", 3],
  ["metal", "planning", 3],
  ["water", "analytical", 3],
  ["head_line_curve", "adaptability", 3],
].forEach((v) => add(...v));
const cond = (field, op, value) => ({ field, op, value });
const definitions = [
  [
    "ENTRY",
    [cond("status", "eq", "unemployed")],
    ["BUILD_SKILL", "GAIN_EXPERIENCE"],
    3,
    "직업 진입이 먼저입니다.",
  ],
  [
    "INVISIBLE_EXPERT",
    [
      cond("leadership", "lt", 45),
      cond("external_visibility", "lt", 40),
      cond("execution", "gte", 65),
    ],
    ["BUILD_LEADERSHIP_EXPERIENCE", "BUILD_EXTERNAL_VISIBILITY"],
    3,
    "실무는 쌓였는데, 당신의 영향력은 회사 안에 갇혀 있습니다.",
  ],
  [
    "MANAGER_WINDOW",
    [
      cond("age", "gte", 40),
      cond("experienceYears", "gte", 10),
      cond("leadership", "lt", 50),
    ],
    ["BUILD_LEADERSHIP_EXPERIENCE"],
    3,
    "경력 연수만으로 관리자가 되지는 않습니다.",
  ],
  [
    "LOW_LEAD",
    [cond("leadership", "lt", 45)],
    ["BUILD_LEADERSHIP_EXPERIENCE"],
    3,
    "혼자 잘하는 것과 팀의 결과를 만드는 것은 다릅니다.",
  ],
  [
    "LOW_VISIBLE",
    [cond("external_visibility", "lt", 45)],
    ["BUILD_EXTERNAL_VISIBILITY"],
    null,
    "회사 밖에 보여줄 결과가 부족합니다.",
  ],
  [
    "NO_RUNWAY",
    [cond("runwayMonths", "lt", 6)],
    ["BUILD_RUNWAY"],
    null,
    "준비 없는 퇴사는 선택지를 줄입니다.",
  ],
  [
    "BUSINESS",
    [cond("concern", "eq", "창업")],
    ["VALIDATE_BUSINESS", "BUILD_RUNWAY"],
    null,
    "사업 아이디어보다 지불할 고객이 먼저입니다.",
  ],
  [
    "MOVE",
    [cond("concern", "eq", "이직")],
    ["DOCUMENT_IMPACT", "BUILD_EXTERNAL_VISIBILITY"],
    null,
    "회사 이름만 바꾸면 같은 한계를 만납니다.",
  ],
  [
    "PROMOTION",
    [cond("concern", "eq", "승진")],
    ["BUILD_LEADERSHIP_EXPERIENCE", "NEGOTIATE"],
    null,
    "승진을 기다리지 말고 상위 역할의 증거를 만드세요.",
  ],
  [
    "NETWORK",
    [cond("networking", "lt", 50)],
    ["BUILD_NETWORK"],
    null,
    "필요할 때만 만드는 인맥은 늦습니다.",
  ],
  [
    "LEARNING",
    [cond("learning_speed", "lt", 50)],
    ["LEARN"],
    null,
    "기존 기술의 유효기간을 점검하세요.",
  ],
  [
    "JUNIOR",
    [cond("experienceYears", "between", [0, 2])],
    ["GAIN_EXPERIENCE"],
    null,
    "지금 필요한 것은 넓은 관심보다 완수 경험입니다.",
  ],
  [
    "SENIOR",
    [cond("experienceYears", "gte", 7)],
    ["DOCUMENT_IMPACT"],
    null,
    "연차를 성과로 번역해야 합니다.",
  ],
  [
    "IT",
    [cond("occupation", "eq", "it")],
    ["BUILD_SKILL"],
    null,
    "기술 목록보다 사용된 결과물을 보여주세요.",
  ],
  [
    "PRODUCT",
    [cond("occupation", "eq", "product")],
    ["BUILD_LEADERSHIP_EXPERIENCE"],
    null,
    "기획서가 아니라 실행 결과를 책임지세요.",
  ],
  [
    "STUDENT",
    [cond("status", "eq", "student")],
    ["GAIN_EXPERIENCE"],
    null,
    "졸업 전에 작은 실무를 경험하세요.",
  ],
  [
    "FREELANCE",
    [cond("status", "eq", "freelance")],
    ["BUILD_NETWORK", "BUILD_RUNWAY"],
    null,
    "한 고객 의존도를 낮추세요.",
  ],
  [
    "INCOME",
    [cond("concern", "eq", "소득")],
    ["NEGOTIATE"],
    null,
    "시간보다 성과의 가격을 설명하세요.",
  ],
  [
    "TRANSITION",
    [cond("concern", "in", ["커리어 전환", "퇴직"])],
    ["BUILD_SKILL", "BUILD_RUNWAY"],
    null,
    "새 역할은 현직에 있을 때 검증하세요.",
  ],
  [
    "LEADER",
    [cond("leadership", "gte", 65), cond("external_visibility", "gte", 60)],
    ["DOCUMENT_IMPACT"],
    null,
    "영향력을 반복 가능한 운영 구조로 바꾸세요.",
  ],
];
const rules = definitions.map(([id, all, actionIds, ceiling], i) => ({
  id,
  priority: 100 - i,
  when: { all },
  actionIds,
  ceiling,
  templateId: id,
}));
const overrides = JSON.parse(
  readFileSync("templates/interpretation-overrides.json", "utf8"),
);
const interpretations = definitions.map(([id, , actionIds, , headline]) => ({
  id,
  variant: "direct",
  headline,
  judgement: headline,
  explanation: "입력한 경력과 행동 증거를 공통 성향 모델로 비교한 판정입니다.",
  criticism: "시간이 해결해 줄 거라는 기대는 실행 계획이 아닙니다.",
  risk: "같은 행동을 반복하면 현재 병목이 남을 수 있습니다.",
  recommendation: actions.find((a) => a.id === actionIds[0]).title,
  action: actions.find((a) => a.id === actionIds[0]).detail,
  scenario:
    "행동을 완료하고 성과로 입증한다는 가정에서 개선 경로를 비교합니다.",
  closing: "다음 분석에서는 의지가 아니라 완료한 증거를 입력하세요.",
  ...overrides[id],
}));
const sectionNames = [
  "타고난 직업 성향",
  "현재 직업 적합도",
  "무직인 경우 유력 직업군",
  "조직형 / 전문가형 / 사업형",
  "적합한 업무환경",
  "리더십 성향",
  "돈을 버는 방식",
  "조직생활 지속 가능성",
  "이직 성향",
  "이직 검토 시기",
  "현재 이직 준비 수준",
  "향후 3년 커리어 흐름",
  "향후 5년 커리어 흐름",
  "추천 직업군",
  "주의할 직업군",
  "관리자 적성",
  "창업 적성",
  "예상 커리어 상한",
  "상한을 높이는 조건",
  "주 커리어 전환 검토 구간",
  "제2커리어 방향",
  "Critical Age",
  "가장 위험한 선택",
  "지금 해야 하는 행동",
  "현재경로 vs 개선경로",
];
const keys = [
  "topTraits",
  "fit",
  "occupations",
  "orientation",
  "environment",
  "leadership",
  "income",
  "organization",
  "mobility",
  "changeAge",
  "readiness",
  "year3",
  "year5",
  "occupations",
  "avoid",
  "management",
  "business",
  "ceiling",
  "actions",
  "retirement",
  "second",
  "critical",
  "risk",
  "firstAction",
  "comparison",
];
write("rules/catalog.json", {
  version: "2.0.0",
  traits,
  occupations,
  mappings,
  rules,
  actions,
  levels: [
    { id: 1, label: "Junior" },
    { id: 2, label: "Professional" },
    { id: 3, label: "Senior" },
    { id: 4, label: "Team / Expert Lead" },
    { id: 5, label: "Executive / Principal" },
  ],
  products: [
    { id: "career-basic", label: "Career Basic", price: 0, enabled: true },
    { id: "career-full", label: "Career Full", price: 9900, enabled: true },
    { id: "relationship", label: "Relationship", price: 0, enabled: false },
    { id: "life-full", label: "Life Full Report", price: 0, enabled: false },
  ],
  scenarioConfig: {
    levelGates: [
      { level: 4, when: { field: "leadership", op: "gte", value: 50 } },
      {
        level: 5,
        when: {
          all: [
            { field: "leadership", op: "gte", value: 65 },
            { field: "external_visibility", op: "gte", value: 60 },
          ],
        },
      },
    ],
    baseCeiling: 3,
    improvedDelta: 1,
    aggressiveDelta: 2,
    criticalOffset: 2,
    retirementFloor: 55,
    retirementOffset: 14,
  },
  domainWeights: {
    career: {
      execution: 0.3,
      specialist_orientation: 0.25,
      leadership: 0.25,
      external_visibility: 0.2,
    },
    money: { money_orientation: 0.5, planning: 0.5 },
    relationship: { communication: 0.5, relationship_stability: 0.5 },
    business: { entrepreneurship: 0.4, risk_tolerance: 0.3, execution: 0.3 },
  },
});
write("templates/reports.json", {
  version: "2.0.0",
  interpretations,
  sections: sectionNames.map((title, i) => ({
    id: `section_${i + 1}`,
    title,
    key: keys[i],
  })),
});
const common = {
  asOf: "2026-09-14",
  birthTime: "12:00",
  gender: "unspecified",
  education: "university",
  incomeBand: "3000-5000",
  jobTitle: "",
  managementYears: 0,
  visibility: 1,
  network: 2,
  learningHours: 4,
  runwayMonths: 4,
  businessInterest: 2,
  concern: "직업선택",
  palm: {
    source: "demo",
    features: {
      head_line_length: 0.65,
      heart_line_length: 0.55,
      life_line_length: 0.7,
    },
  },
  selfRatings: {},
};
write("rules/demos.json", [
  {
    ...common,
    id: "A",
    name: "진입의 갈림길",
    birthDate: "1997-04-20",
    status: "unemployed",
    occupation: "it",
    experienceYears: 0,
    level: 1,
  },
  {
    ...common,
    id: "B",
    name: "보이지 않는 시니어",
    birthDate: "1991-02-18",
    status: "employed",
    occupation: "it",
    experienceYears: 8,
    level: 3,
    jobTitle: "개발자",
    concern: "이직",
  },
  {
    ...common,
    id: "C",
    name: "관리자로 넘어갈 때",
    birthDate: "1985-06-12",
    status: "employed",
    occupation: "product",
    experienceYears: 15,
    level: 3,
    jobTitle: "기획 / 관리",
    concern: "승진",
  },
]);
