import { writeFileSync, mkdirSync } from "node:fs";
const groups = [
  [
    "IT_DEVELOPMENT",
    "IT / 개발",
    "it",
    "SOFTWARE_ENGINEER",
    "소프트웨어 개발",
    ["BACKEND_ENGINEER", "백엔드 개발자"],
    ["FRONTEND_ENGINEER", "프론트엔드 개발자"],
    ["DATA_ENGINEER", "데이터 엔지니어"],
  ],
  [
    "STRATEGY",
    "기획 / 전략",
    "product",
    "PLANNER",
    "기획",
    ["PRODUCT_PLANNER", "서비스 기획자"],
    ["STRATEGY_PLANNER", "전략 기획자"],
  ],
  [
    "SALES",
    "영업",
    "sales",
    "SALES_PROFESSIONAL",
    "영업",
    ["B2B_SALES", "기업 영업"],
  ],
  [
    "MARKETING",
    "마케팅",
    "marketing",
    "MARKETER",
    "마케팅",
    ["DIGITAL_MARKETER", "디지털 마케터"],
  ],
  [
    "DESIGN",
    "디자인",
    "design",
    "DESIGNER",
    "디자인",
    ["PRODUCT_DESIGNER", "프로덕트 디자이너"],
  ],
  [
    "SCM",
    "물류 / SCM",
    "logistics",
    "SCM_PROFESSIONAL",
    "물류",
    ["SCM_PLANNER", "SCM 담당자"],
  ],
  [
    "PRODUCTION",
    "생산",
    "manufacturing",
    "PRODUCTION_PROFESSIONAL",
    "생산",
    ["PRODUCTION_MANAGER", "생산 담당자"],
  ],
  [
    "QUALITY",
    "품질",
    "engineering",
    "QUALITY_ENGINEER",
    "품질 관리",
    ["QUALITY_SPECIALIST", "품질 담당자"],
  ],
  [
    "RND",
    "연구개발",
    "research",
    "RESEARCHER",
    "연구개발",
    ["RND_RESEARCHER", "연구개발 연구원"],
  ],
  [
    "ACCOUNTING",
    "재무 / 회계",
    "finance",
    "ACCOUNTANT",
    "재무 회계",
    ["FINANCIAL_ACCOUNTANT", "회계 담당자"],
  ],
  [
    "HR",
    "인사 / 조직",
    "hr",
    "HR_PROFESSIONAL",
    "인사",
    ["HR_MANAGER", "인사 담당자"],
  ],
  [
    "EDUCATION",
    "교육",
    "education",
    "EDUCATOR",
    "교육",
    ["TEACHER", "교육 전문가"],
  ],
  [
    "HEALTHCARE",
    "의료",
    "healthcare",
    "HEALTH_PROFESSIONAL",
    "의료",
    ["HEALTH_SPECIALIST", "의료 전문가"],
  ],
  [
    "FINANCIAL",
    "금융",
    "finance",
    "FINANCE_PROFESSIONAL",
    "금융",
    ["FINANCE_ANALYST", "금융 분석가"],
  ],
  [
    "PUBLIC",
    "공공 / 행정",
    "public",
    "PUBLIC_OFFICER",
    "공공 행정",
    ["ADMINISTRATOR", "행정 담당자"],
  ],
  [
    "PROFESSIONAL",
    "전문직",
    "legal",
    "PROFESSIONAL",
    "전문직",
    ["LEGAL_PROFESSIONAL", "법률 전문가"],
  ],
  [
    "SERVICE",
    "서비스",
    "service",
    "SERVICE_PROFESSIONAL",
    "서비스",
    ["SERVICE_SPECIALIST", "서비스 담당자"],
  ],
  [
    "SELF_EMPLOYED",
    "자영업",
    "business",
    "SELF_EMPLOYED",
    "자영업",
    ["SHOP_OWNER", "매장 운영자"],
  ],
  [
    "ENTREPRENEURSHIP",
    "사업 / 창업",
    "business",
    "BUSINESS_OWNER",
    "사업",
    ["FOUNDER", "창업자"],
  ],
  [
    "OTHER",
    "기타",
    "operations",
    "OTHER",
    "기타 / 직접 입력",
    ["OTHER", "기타 / 직접 입력"],
  ],
];
const occupations = groups.flatMap(
  ([
    categoryCode,
    categoryLabel,
    legacyCode,
    jobCode,
    jobLabel,
    ...specialties
  ]) =>
    specialties.map(([specialtyCode, specialtyLabel]) => ({
      categoryCode,
      categoryLabel,
      legacyCode,
      jobCode,
      jobLabel,
      specialtyCode,
      specialtyLabel,
    })),
);
const roleLabels = {
  ENTRY: "업무를 배우며 수행하는 단계",
  INDEPENDENT_CONTRIBUTOR: "독립 실무자",
  KEY_CONTRIBUTOR: "핵심 실무자",
  LEAD: "프로젝트 / 소규모 팀 리드",
  TEAM_MANAGER: "팀 단위 관리 역할",
  ORG_LEADER: "여러 팀 / 조직 책임 역할",
  EXECUTIVE_BUSINESS: "임원 / 사업 책임 역할",
  NOT_APPLICABLE: "해당 없음",
};
const managementLabels = {
  NONE: "없음",
  PEER_MENTORING: "후배 / 동료 업무 지원",
  PROJECT_LEAD: "프로젝트 리더",
  TEAM_2_5: "2–5명 팀 리딩",
  TEAM_6_15: "6–15명 조직 관리",
  ORG_16_PLUS: "16명 이상 조직 관리",
  MULTI_TEAM: "여러 팀 / 조직 책임",
};
const data = {
  version: "2.0.0",
  occupations,
  roleLabels,
  managementLabels,
  roleStages: {
    ENTRY: 1,
    INDEPENDENT_CONTRIBUTOR: 2,
    KEY_CONTRIBUTOR: 3,
    LEAD: 4,
    TEAM_MANAGER: 4,
    ORG_LEADER: 5,
    EXECUTIVE_BUSINESS: 5,
    NOT_APPLICABLE: 1,
  },
  managementSignals: {
    NONE: -0.5,
    PEER_MENTORING: -0.25,
    PROJECT_LEAD: 0,
    TEAM_2_5: 0.2,
    TEAM_6_15: 0.5,
    ORG_16_PLUS: 0.8,
    MULTI_TEAM: 1,
  },
  trackWeights: {
    MANAGEMENT: {
      leadership: 0.4,
      management_orientation: 0.3,
      persuasion: 0.15,
      responsibility: 0.15,
    },
    EXPERT: {
      specialist_orientation: 0.4,
      execution: 0.3,
      learning_speed: 0.15,
      analytical: 0.15,
    },
  },
  hybridGap: 8,
  stageLabels: {
    MANAGEMENT: [
      "업무 진입 단계",
      "독립 실무 역할",
      "핵심 실무 역할",
      "프로젝트 리드 ~ 팀장급 역할",
      "조직 책임 ~ 사업 책임 역할",
    ],
    EXPERT: [
      "전문 업무 진입 단계",
      "독립 전문 실무",
      "선임·핵심 전문 실무",
      "고급 전문 ~ 조직 대표 전문 역할",
      "최상위 전문 영향력 역할",
    ],
    HYBRID: [
      "업무 진입 단계",
      "독립 실무 역할",
      "핵심 실무 ~ 선임 전문 역할",
      "프로젝트 리드 ~ 상위 전문가 역할",
      "조직 책임 ~ 최상위 전문 영향력 역할",
    ],
  },
};
mkdirSync("rules", { recursive: true });
writeFileSync("rules/career-model.json", JSON.stringify(data, null, 2));
writeFileSync(
  "templates/speech.json",
  JSON.stringify(
    {
      DIRECT: {
        opening: "{{salutation}}\n{{judgement}}",
        blocker:
          "{{displayName}}, 지금 막히는 건 {{blocker}}이야.\n{{explanation}}",
        action: "{{displayName}}, 먼저 이 기록부터 만들어.\n{{action}}",
        closing:
          "{{displayName}}, 다음에는 계획이 아니라 완료한 기록으로 다시 보자.",
      },
      POLITE: {
        opening: "{{displayName}}님.\n{{judgement}}",
        blocker: "지금 확인해야 할 병목은 {{blocker}}입니다.\n{{explanation}}",
        action: "먼저 이 행동을 실무 기록으로 남겨주세요.\n{{action}}",
        closing:
          "{{displayName}}님, 다음에는 완료한 기록을 바탕으로 경로를 다시 점검하겠습니다.",
      },
    },
    null,
    2,
  ),
);
