-- LIMIT U ownership-first schema. All report details share a session-owner composite FK.
create table public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
alter table public.admin_users enable row level security;
grant select on public.admin_users to authenticated;
create policy admin_self on public.admin_users for select to authenticated using (user_id=(select auth.uid()));
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.profiles enable row level security;
grant select,insert,update,delete on public.profiles to authenticated;
create policy own_profile on public.profiles for all to authenticated using (id=(select auth.uid())) with check(id=(select auth.uid()));
create table public.analysis_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, input jsonb not null, created_at timestamptz not null default now(), unique(id,user_id));
alter table public.analysis_sessions enable row level security;
grant select,insert,delete on public.analysis_sessions to authenticated;
create policy own_session on public.analysis_sessions for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index sessions_owner_created on public.analysis_sessions(user_id,created_at desc);
create table public.palm_analyses (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.palm_analyses enable row level security;
grant select,insert,delete on public.palm_analyses to authenticated;
create policy own_palm_analyses on public.palm_analyses for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index palm_analyses_owner_session on public.palm_analyses(user_id,session_id);
create table public.palm_features (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.palm_features enable row level security;
grant select,insert,delete on public.palm_features to authenticated;
create policy own_palm_features on public.palm_features for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index palm_features_owner_session on public.palm_features(user_id,session_id);
create table public.saju_profiles (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.saju_profiles enable row level security;
grant select,insert,delete on public.saju_profiles to authenticated;
create policy own_saju_profiles on public.saju_profiles for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index saju_profiles_owner_session on public.saju_profiles(user_id,session_id);
create table public.saju_features (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.saju_features enable row level security;
grant select,insert,delete on public.saju_features to authenticated;
create policy own_saju_features on public.saju_features for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index saju_features_owner_session on public.saju_features(user_id,session_id);
create table public.career_profiles (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.career_profiles enable row level security;
grant select,insert,delete on public.career_profiles to authenticated;
create policy own_career_profiles on public.career_profiles for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index career_profiles_owner_session on public.career_profiles(user_id,session_id);
create table public.name_features (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.name_features enable row level security;
grant select,insert,delete on public.name_features to authenticated;
create policy own_name_features on public.name_features for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index name_features_owner_session on public.name_features(user_id,session_id);
create table public.life_context_features (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.life_context_features enable row level security;
grant select,insert,delete on public.life_context_features to authenticated;
create policy own_life_context_features on public.life_context_features for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index life_context_features_owner_session on public.life_context_features(user_id,session_id);
create table public.trait_scores (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.trait_scores enable row level security;
grant select,insert,delete on public.trait_scores to authenticated;
create policy own_trait_scores on public.trait_scores for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index trait_scores_owner_session on public.trait_scores(user_id,session_id);
create table public.career_scores (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.career_scores enable row level security;
grant select,insert,delete on public.career_scores to authenticated;
create policy own_career_scores on public.career_scores for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index career_scores_owner_session on public.career_scores(user_id,session_id);
create table public.money_scores (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.money_scores enable row level security;
grant select,insert,delete on public.money_scores to authenticated;
create policy own_money_scores on public.money_scores for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index money_scores_owner_session on public.money_scores(user_id,session_id);
create table public.relationship_scores (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.relationship_scores enable row level security;
grant select,insert,delete on public.relationship_scores to authenticated;
create policy own_relationship_scores on public.relationship_scores for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index relationship_scores_owner_session on public.relationship_scores(user_id,session_id);
create table public.business_scores (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.business_scores enable row level security;
grant select,insert,delete on public.business_scores to authenticated;
create policy own_business_scores on public.business_scores for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index business_scores_owner_session on public.business_scores(user_id,session_id);
create table public.career_scenarios (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.career_scenarios enable row level security;
grant select,insert,delete on public.career_scenarios to authenticated;
create policy own_career_scenarios on public.career_scenarios for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index career_scenarios_owner_session on public.career_scenarios(user_id,session_id);
create table public.critical_points (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.critical_points enable row level security;
grant select,insert,delete on public.critical_points to authenticated;
create policy own_critical_points on public.critical_points for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index critical_points_owner_session on public.critical_points(user_id,session_id);
create table public.recommended_actions (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.recommended_actions enable row level security;
grant select,insert,delete on public.recommended_actions to authenticated;
create policy own_recommended_actions on public.recommended_actions for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index recommended_actions_owner_session on public.recommended_actions(user_id,session_id);
create table public.report_sections (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.report_sections enable row level security;
grant select,insert,delete on public.report_sections to authenticated;
create policy own_report_sections on public.report_sections for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index report_sections_owner_session on public.report_sections(user_id,session_id);
create table public.reports (id uuid primary key default gen_random_uuid(), session_id uuid not null, user_id uuid not null, data jsonb not null, rule_version text not null, template_version text not null, created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.analysis_sessions(id,user_id) on delete cascade);
alter table public.reports enable row level security;
grant select,insert,delete on public.reports to authenticated;
create policy own_reports on public.reports for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create index reports_owner_session on public.reports(user_id,session_id);
create table public.trait_definitions (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.trait_definitions enable row level security;
grant select on public.trait_definitions to anon,authenticated;
grant insert on public.trait_definitions to authenticated;
create policy read_trait_definitions on public.trait_definitions for select to anon,authenticated using(true);
create policy admin_insert_trait_definitions on public.trait_definitions for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.trait_source_weights (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.trait_source_weights enable row level security;
grant select on public.trait_source_weights to anon,authenticated;
grant insert on public.trait_source_weights to authenticated;
create policy read_trait_source_weights on public.trait_source_weights for select to anon,authenticated using(true);
create policy admin_insert_trait_source_weights on public.trait_source_weights for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.rule_definitions (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.rule_definitions enable row level security;
grant select on public.rule_definitions to anon,authenticated;
grant insert on public.rule_definitions to authenticated;
create policy read_rule_definitions on public.rule_definitions for select to anon,authenticated using(true);
create policy admin_insert_rule_definitions on public.rule_definitions for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.interpretation_definitions (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.interpretation_definitions enable row level security;
grant select on public.interpretation_definitions to anon,authenticated;
grant insert on public.interpretation_definitions to authenticated;
create policy read_interpretation_definitions on public.interpretation_definitions for select to anon,authenticated using(true);
create policy admin_insert_interpretation_definitions on public.interpretation_definitions for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.report_templates (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.report_templates enable row level security;
grant select on public.report_templates to anon,authenticated;
grant insert on public.report_templates to authenticated;
create policy read_report_templates on public.report_templates for select to anon,authenticated using(true);
create policy admin_insert_report_templates on public.report_templates for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.occupation_categories (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.occupation_categories enable row level security;
grant select on public.occupation_categories to anon,authenticated;
grant insert on public.occupation_categories to authenticated;
create policy read_occupation_categories on public.occupation_categories for select to anon,authenticated using(true);
create policy admin_insert_occupation_categories on public.occupation_categories for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.action_definitions (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.action_definitions enable row level security;
grant select on public.action_definitions to anon,authenticated;
grant insert on public.action_definitions to authenticated;
create policy read_action_definitions on public.action_definitions for select to anon,authenticated using(true);
create policy admin_insert_action_definitions on public.action_definitions for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.career_levels (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.career_levels enable row level security;
grant select on public.career_levels to anon,authenticated;
grant insert on public.career_levels to authenticated;
create policy read_career_levels on public.career_levels for select to anon,authenticated using(true);
create policy admin_insert_career_levels on public.career_levels for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.products (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.products enable row level security;
grant select on public.products to anon,authenticated;
grant insert on public.products to authenticated;
create policy read_products on public.products for select to anon,authenticated using(true);
create policy admin_insert_products on public.products for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.catalog_versions (id text not null, version text not null, data jsonb not null, created_at timestamptz not null default now(), primary key(id,version));
alter table public.catalog_versions enable row level security;
grant select on public.catalog_versions to anon,authenticated;
grant insert on public.catalog_versions to authenticated;
create policy read_catalog_versions on public.catalog_versions for select to anon,authenticated using(true);
create policy admin_insert_catalog_versions on public.catalog_versions for insert to authenticated with check(exists(select 1 from public.admin_users where user_id=(select auth.uid())));
create table public.payments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, product_id text not null, product_version text not null, amount integer not null check(amount>=0), provider text not null check(provider in ('mock','toss')), status text not null check(status in ('pending','simulated','paid','failed','refunded')), idempotency_key uuid not null unique, provider_reference text unique, created_at timestamptz not null default now(), foreign key(product_id,product_version) references public.products(id,version));
alter table public.payments enable row level security;
grant select on public.payments to authenticated;
create policy own_payments on public.payments for select to authenticated using(user_id=(select auth.uid()));
create index payments_owner on public.payments(user_id,created_at desc);
create index payments_product on public.payments(product_id,product_version);
-- SECURITY INVOKER: ownership is enforced by every target table, including composite FKs.
create function public.save_analysis(payload jsonb) returns uuid language plpgsql security invoker set search_path='' as $$
declare sid uuid; uid uuid := auth.uid(); item text;
begin
 if uid is null then raise exception 'Authentication required'; end if;
 insert into public.analysis_sessions(user_id,input) values(uid,payload->'input') returning id into sid;
 insert into public.reports(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload,payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.career_profiles(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'input',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.palm_analyses(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'input'->'palm',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.palm_features(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'input'->'palm'->'features',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.saju_profiles(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'saju',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.saju_features(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'saju'->'features',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.trait_scores(session_id,user_id,data,rule_version,template_version) values(sid,uid,jsonb_build_object('scores',payload->'traits','evidence',payload->'evidence'),payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.career_scenarios(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'scenarios',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.critical_points(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'criticalPoints',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.recommended_actions(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'actions',payload->>'ruleVersion',payload->>'templateVersion');
 insert into public.report_sections(session_id,user_id,data,rule_version,template_version) values(sid,uid,payload->'sections',payload->>'ruleVersion',payload->>'templateVersion');
 return sid;
end $$;
revoke all on function public.save_analysis(jsonb) from public,anon;
grant execute on function public.save_analysis(jsonb) to authenticated;
